<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0-preview.1.25081.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.0-preview.1.25081.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0-preview.1.25081.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\AriaHR.Modules.Organization.Application.csproj" />
    <ProjectReference Include="..\Domain\AriaHR.Modules.Organization.Domain.csproj" />
    <ProjectReference Include="..\..\Identity\Domain\AriaHR.Modules.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\Identity\Application\AriaHR.Modules.Identity.Application.csproj" />
    <ProjectReference Include="..\..\Identity\Infrastructure\AriaHR.Modules.Identity.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
